#URLS
baseurl: "https://www.alexis.computer"
# Config
config: "config.yaml"
# CanonifyUrls: true
# Site settings
MetaDataFormat: "yaml"
languageCode: "us-en"

#Robots
enableRobotsTXT: false

# Site Params
title: "Alexis La Porte: Web Developer"
params:
  email: aklaporte@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
    My personal website.
  author: Alexis La Porte
# Paths
publishDir: "public"
contentDir: "content"
layoutDir: "layouts"
# Theme
themeDir: "themes"

buildDrafts: false
# Navbar
menu: 
  main:
# Social Media
github_username:  aklap

permalinks:
  post: /posts/:year/:month/:day/:slug
Paginate: 5
PaginatePath: page

